import { app, BrowserWindow, ipcMain } from "electron";
import { spawn } from "child_process";
import {
    existsSync,
    mkdirSync,
    readFileSync,
    unlinkSync,
    renameSync,
    createWriteStream,
    mkdtempSync,
    rmdirSync,
} from "fs";
import path from "path";
import https from "https";
import os from "os";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const DOWNLOAD_DIRECTORY =
    "C:\\Users\\chris\\OneDrive\\Music\\iTunes\\iTunes Media\\Automatically Add to Apple Music";

const NodeID3 = require("node-id3");

function getMetadata(url: string): Promise<any> {
    return new Promise((resolve, reject) => {
        const proc = spawn("yt-dlp", ["--print-json", url], {
            windowsHide: true,
        });
        let stdout = "";
        proc.stdout.on("data", (chunk: Buffer) => (stdout += chunk.toString()));
        proc.on("close", (code: number) => {
            if (code === 0) {
                try {
                    const data = JSON.parse(stdout.trim());
                    resolve(data);
                } catch (e) {
                    reject(new Error("Failed to parse metadata"));
                }
            } else {
                reject(new Error("Failed to get metadata"));
            }
        });
        proc.on("error", reject);
    });
}

function downloadMp3(url: string, output: string): Promise<void> {
    return new Promise((resolve, reject) => {
        const proc = spawn(
            "yt-dlp",
            ["-x", "--audio-format", "mp3", "--output", output, url],
            { windowsHide: true },
        );
        proc.on("close", (code: number) => {
            if (code === 0) resolve();
            else reject(new Error(`Download failed with code ${code}`));
        });
        proc.on("error", reject);
    });
}

function downloadThumbnail(url: string, output: string): Promise<void> {
    return new Promise((resolve, reject) => {
        const file = createWriteStream(output);
        https
            .get(url, (res) => {
                res.pipe(file);
                file.on("finish", () => {
                    file.close();
                    resolve();
                });
            })
            .on("error", (err) => {
                unlinkSync(output);
                reject(err);
            });
    });
}

ipcMain.handle(
    "download-mp3",
    async (_event, data: { url: string; title?: string; artist?: string }) => {
        const { url, title: customTitle, artist: customArtist } = data;
        if (typeof url !== "string" || !url.trim()) {
            throw new Error("URL is required");
        }

        if (!existsSync(DOWNLOAD_DIRECTORY)) {
            mkdirSync(DOWNLOAD_DIRECTORY, { recursive: true });
        }

        // Create temp directory
        const tempDir = mkdtempSync(path.join(os.tmpdir(), "saggysonic-"));

        // Get metadata
        const metadata = await getMetadata(url);
        const finalTitle = customTitle || metadata.title || "Unknown Title";
        const finalArtist =
            customArtist || metadata.uploader || "Unknown Artist";
        const thumbnailUrl = metadata.thumbnail;

        // Download MP3 to temp
        const tempOutput = path.join(tempDir, "temp_download.mp3");
        await downloadMp3(url, tempOutput);

        // Download thumbnail to temp
        const thumbnailPath = path.join(tempDir, "temp_thumb.jpg");
        let imageBuffer: Buffer | undefined;
        if (thumbnailUrl) {
            await downloadThumbnail(thumbnailUrl, thumbnailPath);
            imageBuffer = readFileSync(thumbnailPath);
        }

        // Set metadata
        const tags: any = {
            title: finalTitle,
            artist: finalArtist,
            album: finalTitle,
        };
        if (imageBuffer) {
            tags.APIC = {
                mime: "image/jpeg",
                type: { id: 3, name: "front cover" },
                imageBuffer,
            };
        }
        NodeID3.write(tags, tempOutput);

        // Rename to final name in temp dir
        const finalName = `${finalTitle} - ${finalArtist}.mp3`.replace(
            /[<>:"/\\|?*]/g,
            "",
        );
        const tempFinalPath = path.join(tempDir, finalName);
        renameSync(tempOutput, tempFinalPath);

        // Move to final directory
        const finalPath = path.join(DOWNLOAD_DIRECTORY, finalName);
        renameSync(tempFinalPath, finalPath);

        // Clean up temp dir
        if (existsSync(thumbnailPath)) unlinkSync(thumbnailPath);
        rmdirSync(tempDir);

        return { success: true, message: "Download complete with metadata." };
    },
);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
    app.quit();
}

const createWindow = (): void => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Open the DevTools.
    mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
