import { app, BrowserWindow, ipcMain, clipboard, dialog } from "electron";
import { spawn } from "child_process";
import {
    existsSync,
    mkdirSync,
    readFileSync,
    unlinkSync,
    renameSync,
    createWriteStream,
    mkdtempSync,
    rmdirSync,
} from "fs";
import path from "path";
import https from "https";
import os from "os";
import Database from "better-sqlite3";
import NodeID3 from "node-id3";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

function getBinPath() {
    const base = app.isPackaged
        ? process.resourcesPath
        : path.join(__dirname, "..", "..");

    let platform: string = process.platform;
    console.log(platform);

    if (platform === "win32") platform = "win";
    if (platform === "darwin") platform = "mac";
    if (platform === "linux") platform = "linux";

    return path.join(base, "src/bin", platform);
}

// Database setup
const userDataPath = app.getPath("userData");
const dbPath = path.join("", "downloads.db");
const db = new Database(dbPath);
db.exec(`CREATE TABLE IF NOT EXISTS downloads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  artist TEXT NOT NULL,
  url TEXT UNIQUE NOT NULL
)`);

// Check if yt-dlp is available
function checkYtDlp(): Promise<void> {
    const binPath = getBinPath();
    return new Promise((resolve, reject) => {
        const proc = spawn(
            path.join(
                binPath,
                process.platform === "win32" ? "yt-dlp.exe" : "yt-dlp",
            ),
            ["--version"],
        );
        proc.on("close", (code: number) => {
            if (code === 0) {
                resolve();
            } else {
                reject(new Error("yt-dlp is not available or not working"));
            }
        });
        proc.on("error", (err) => {
            reject(new Error(`yt-dlp not found: ${err.message}`));
        });
    });
}

// Download queue
const downloadQueue: Array<{
    url: string;
    title?: string;
    artist?: string;
    directory: string;
    startTime?: string;
    endTime?: string;
}> = [];
let isProcessing = false;
let currentDownloading: {
    url: string;
    title?: string;
    artist?: string;
} | null = null;

// Progress tracking
let currentProgress = 0;
let mainWindow: BrowserWindow | null = null;

function getMetadata(url: string): Promise<any> {
    return new Promise((resolve, reject) => {
        const proc = spawn("yt-dlp", ["--print-json", url]);
        let stdout = "";
        let stderr = "";
        proc.stdout.on("data", (chunk: Buffer) => (stdout += chunk.toString()));
        proc.stderr.on("data", (chunk: Buffer) => (stderr += chunk.toString()));
        proc.on("close", (code: number) => {
            if (code === 0) {
                try {
                    const data = JSON.parse(stdout.trim());
                    resolve(data);
                } catch (e) {
                    reject(new Error("Failed to parse metadata"));
                }
            } else {
                reject(
                    new Error(
                        `Failed to get metadata: ${stderr.trim() || "Unknown error"}`,
                    ),
                );
            }
        });
        proc.on("error", reject);
    });
}

function downloadMp3(
    url: string,
    output: string,
    startTime?: string,
    endTime?: string,
): Promise<void> {
    return new Promise((resolve, reject) => {
        const args = [
            "-x",
            "--no-keep-video",
            "--audio-format",
            "mp3",
            "--output",
            output,
        ];

        // Add download-sections if start or end time is provided
        if (startTime || endTime) {
            const start = startTime || "0:00";
            const end = endTime || "100%";
            args.push("--download-sections", `*${start}-${end}`);
        }

        args.push(url);

        const proc = spawn("yt-dlp", args);
        let stderr = "";
        proc.stderr.on("data", (chunk: Buffer) => {
            const chunkStr = chunk.toString();
            stderr += chunkStr;

            // Parse progress percentage from yt-dlp output
            // yt-dlp outputs progress like: [download] 25.5% of ~1234MiB at 1.23MiB/s
            const progressMatch = chunkStr.match(/\[download\]\s+([\d.]+)%/);
            if (progressMatch) {
                const progress = Math.min(
                    Math.round(parseFloat(progressMatch[1])),
                    100,
                );
                currentProgress = progress;
                if (mainWindow) {
                    mainWindow.webContents.send("download-progress", progress);
                }
            }
        });
        proc.on("close", (code: number) => {
            if (code === 0) {
                currentProgress = 0;
                resolve();
            } else
                reject(
                    new Error(
                        `Download failed: ${stderr.trim() || `code ${code}`}`,
                    ),
                );
        });
        proc.on("error", reject);
    });
}

function downloadThumbnail(url: string, output: string): Promise<void> {
    return new Promise((resolve, reject) => {
        const file = createWriteStream(output);
        https
            .get(url, (res) => {
                res.pipe(file);
                file.on("finish", () => {
                    file.close();
                    resolve();
                });
            })
            .on("error", (err) => {
                unlinkSync(output);
                reject(err);
            });
    });
}

async function downloadItem(item: {
    url: string;
    title?: string;
    artist?: string;
    directory: string;
    startTime?: string;
    endTime?: string;
}) {
    const {
        url,
        title: customTitle,
        artist: customArtist,
        directory,
        startTime,
        endTime,
    } = item;
    const downloadDirectory =
        typeof directory === "string" ? directory.trim() : "";

    if (!downloadDirectory) {
        throw new Error("Download directory is required");
    }

    if (!existsSync(downloadDirectory)) {
        mkdirSync(downloadDirectory, { recursive: true });
    }
    if (typeof url !== "string" || !url.trim()) {
        throw new Error("URL is required");
    }

    // Create temp directory
    const tempDir = mkdtempSync(path.join(os.tmpdir(), "saggysonic-"));

    // Get metadata
    const metadata = await getMetadata(url);
    const finalTitle = customTitle || metadata.title || "Unknown Title";
    const finalArtist = customArtist || metadata.uploader || "Unknown Artist";
    const thumbnailUrl = metadata.thumbnail;

    // Download MP3 to temp
    const tempOutput = path.join(tempDir, "temp_download.mp3");
    await downloadMp3(url, tempOutput, startTime, endTime);

    // Download thumbnail to temp
    const thumbnailPath = path.join(tempDir, "temp_thumb.jpg");
    let imageBuffer: Buffer | undefined;
    if (thumbnailUrl) {
        await downloadThumbnail(thumbnailUrl, thumbnailPath);
        imageBuffer = readFileSync(thumbnailPath);
    }

    // Set metadata
    const tags: any = {
        title: finalTitle,
        artist: finalArtist,
        album: finalTitle,
    };
    if (imageBuffer) {
        tags.APIC = {
            mime: "image/jpeg",
            type: { id: 3, name: "front cover" },
            imageBuffer,
        };
    }
    NodeID3.write(tags, tempOutput);

    // Rename to final name in temp dir
    const finalName = `${finalTitle} - ${finalArtist}.mp3`.replace(
        /[<>:"/\\|?*]/g,
        "",
    );
    const tempFinalPath = path.join(tempDir, finalName);
    renameSync(tempOutput, tempFinalPath);

    // Move to final directory
    const finalPath = path.join(downloadDirectory, finalName);
    renameSync(tempFinalPath, finalPath);

    // Clean up temp dir
    if (existsSync(thumbnailPath)) unlinkSync(thumbnailPath);
    rmdirSync(tempDir);

    return { success: true, title: finalTitle, artist: finalArtist };
}

function processQueue() {
    if (isProcessing || downloadQueue.length === 0) return;
    isProcessing = true;
    const item = downloadQueue.shift()!;
    currentDownloading = item;
    downloadItem(item)
        .then(() => {
            db.prepare(
                "INSERT INTO downloads (title, artist, url) VALUES (?, ?, ?)",
            ).run(item.title || "Unknown", item.artist || "Unknown", item.url);
            currentDownloading = null;
            isProcessing = false;
            processQueue();
        })
        .catch((err) => {
            console.error("Download failed:", err);
            currentDownloading = null;
            isProcessing = false;
            processQueue();
        });
}

ipcMain.handle(
    "add-to-queue",
    async (
        _event,
        data: {
            url: string;
            title?: string;
            artist?: string;
            directory: string;
            startTime?: string;
            endTime?: string;
        },
    ) => {
        if (!data.directory || !data.directory.trim()) {
            return {
                success: false,
                message: "Download directory is required.",
            };
        }

        const exists = db
            .prepare("SELECT id FROM downloads WHERE url = ?")
            .get(data.url);
        if (exists) {
            return {
                success: false,
                message: "Duplicate URL detected, skipping.",
            };
        } else {
            downloadQueue.push(data);
            processQueue();
            return { success: true, message: "Added to queue." };
        }
    },
);

ipcMain.handle("select-download-directory", async () => {
    const result = await dialog.showOpenDialog({
        properties: ["openDirectory"],
    });
    if (result.canceled || result.filePaths.length === 0) {
        return null;
    }
    return result.filePaths[0];
});

ipcMain.handle("get-history", () => {
    return db.prepare("SELECT * FROM downloads ORDER BY id DESC").all();
});

ipcMain.handle("delete-history", (_event, id: number) => {
    db.prepare("DELETE FROM downloads WHERE id = ?").run(id);
    return { success: true };
});

ipcMain.handle("get-clipboard", () => {
    return clipboard.readText();
});

ipcMain.handle("get-queue", () => downloadQueue);

ipcMain.handle("get-current-downloading", () => currentDownloading);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
    app.quit();
}

const createWindow = (): void => {
    // Create the browser window.
    const window = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    mainWindow = window;

    // and load the index.html of the app.
    window.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

    // Open the DevTools.
    window.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
    try {
        await checkYtDlp();
        createWindow();
    } catch (error) {
        console.error("yt-dlp check failed:", error);
        // For now, still create window, but show error
        createWindow();
        // Perhaps send to renderer to show error
    }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
